import "../../assets/style/globals.css";
import "../../assets/style/swiper.css";
import "../../assets/style/loader.css";

import { Geist, Quicksand } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Header from "@/components/layout/header";
import ReduxProvider from "@/components/layout/redux-provider";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata = {
  title: "Caucasync",
  icons: {
    icon: "/icons/logo.ico",
  },
  description: "Generated by Esi",
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${quicksand.variable} antialiased`}>
        <NextIntlClientProvider>
          <ReduxProvider>
            <Header />
            <main>{children}</main>
            <Footer />
            <Toaster className="font-semibold" />
          </ReduxProvider>
        </NextIntlClientProvider>

        {/* <div id="banner" className="h-[100vh] flex items-center p-[20px] justify-center">
          <div className="bg-[#00000079] h-[300px] flex items-center justify-center  w-full  md:w-1/2 p-[50px] rounded-[20px]">
            <h1 className=" text-[30px] lg:text-[40px] w-full text-center text-shadow-accent text-[#fff]  font-semibold">
              Ən qısa zamanda xidmətinizdəyik...
            </h1>
          </div>
        </div> */}
      </body>
    </html>
  );
}
