import "../../assets/style/globals.css";
import "../../assets/style/swiper.css";
import "../../assets/style/loader.css";

import { Geist, Quicksand } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Header from "@/components/layout/header";
import ReduxProvider from "@/components/layout/redux-provider";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

async function getSettings() {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/v1/settings`,
      { next: { revalidate: 3600 } } 
    );
    const data = await response.json();
    return data.data;
  } catch (error) {
    console.error("Settings yükləmə xətası:", error);
    return null;
  }
}

export async function generateMetadata() {
  const settings = await getSettings();

  return {
    title: settings?.meta_title || settings?.site_name || "Caucasync",
    description: settings?.meta_description || "Generated by Esi",
    icons: {
      icon: settings?.favicon 
        ? `${process.env.NEXT_PUBLIC_API_BASE_URL}${settings.favicon}`
        : "/icons/logo.ico",
    },
    openGraph: {
      title: settings?.meta_title || settings?.site_name,
      description: settings?.meta_description,
      image: settings?.og_image 
        ? `${process.env.NEXT_PUBLIC_API_BASE_URL}${settings.og_image}`
        : undefined,
    },
    twitter: {
      card: settings?.twitter_card || "summary_large_image",
    },
  };
}

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <head>
        {/* Canonical URL */}
        {/* <link rel="canonical" href={settings?.canonical_url} /> */}
      </head>
      <body className={`${geistSans.variable} ${quicksand.variable} antialiased`}>
        <NextIntlClientProvider>
          <ReduxProvider>
            <Header />
            <main>{children}</main>
            <Footer />
            <Toaster className="font-semibold" />
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}